### ISSUE TITLE
Problem with running Netlify function: Cannot find module '../build/Release/sharp.node'

### ISSUE THREAD

**Issue by caramiki** [netlify/zip-it-and-ship-it#79] opened 2020-01-15 21:41 UTC
**- Do you want to request a *feature* or report a *bug*?**
bug

**- What is the current behavior?**
I'm including the [sharp](https://sharp.pixelplumbing.com/en/stable/) module in my `deploy-building.js` Netlify function. I'm resizing some images and uploading them to an S3 bucket.

When invoking the function in the Netlify dev environment, it works. However, when I deploy my feature branch in a deploy preview, it does not work. These are the logs from building the site (that are relevant to sharp):

```
3:15:43 PM: Different functions path detected, going to use the one specified in the Netlify configuration file: 'functions/' versus '' in the Netlify UI
3:15:43 PM: Creating functions prep folder
3:15:43 PM: Starting build script
3:15:43 PM: Installing dependencies
3:15:45 PM: Started restoring cached node version
3:15:52 PM: Finished restoring cached node version
3:15:53 PM: v10.18.1 is already installed.
3:15:55 PM: Now using node v10.18.1 (npm v6.13.4)
3:15:55 PM: Attempting ruby version 2.6.2, read from environment
3:15:57 PM: Using ruby version 2.6.2
3:15:57 PM: Using PHP version 5.6
3:15:57 PM: Started restoring cached node modules
3:15:57 PM: Finished restoring cached node modules
3:15:58 PM: Installing NPM modules using NPM version 6.13.4
3:16:12 PM: > sharp@0.23.4 install /opt/build/repo/node_modules/sharp
3:16:12 PM: > (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
3:16:12 PM: info
3:16:12 PM: sharp
3:16:12 PM:  Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.8.1/libvips-8.8.1-linux-x64.tar.gz
3:16:17 PM: npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.0 (node_modules/chokidar/node_modules/fsevents):
3:16:17 PM: npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.0: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
3:16:17 PM: npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
3:16:17 PM: npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
3:16:17 PM: added 41 packages from 148 contributors and audited 20682 packages in 17.73s
.
.
.
3:16:49 PM: Function Dir: /opt/build/repo/functions
3:16:49 PM: TempDir: /tmp/zisi-5e1f80e7ef244ae910e5a4cc
3:16:49 PM: Prepping functions with zip-it-and-ship-it 0.3.1
3:16:51 PM: [ { path: '/tmp/zisi-5e1f80e7ef244ae910e5a4cc/deploy-building.zip',
3:16:51 PM:     runtime: 'js' },
3:16:51 PM:   { path: '/tmp/zisi-5e1f80e7ef244ae910e5a4cc/submission-created.zip',
3:16:51 PM:     runtime: 'js' } ]
3:16:51 PM: Prepping functions complete
3:16:51 PM: Caching artifacts
3:16:51 PM: Started saving node modules
3:16:51 PM: Finished saving node modules
3:16:51 PM: Started saving pip cache
3:16:51 PM: Finished saving pip cache
3:16:51 PM: Started saving emacs cask dependencies
3:16:51 PM: Finished saving emacs cask dependencies
3:16:51 PM: Started saving maven dependencies
3:16:51 PM: Finished saving maven dependencies
3:16:51 PM: Started saving boot dependencies
3:16:52 PM: Finished saving boot dependencies
3:16:52 PM: Started saving go dependencies
3:16:52 PM: Finished saving go dependencies
3:16:52 PM: Build script success
```

Here are the function's logs when it tries to run:

```
3:15:26 PM: 2020-01-15T21:15:26.407Z	undefined	ERROR	
Something went wrong installing the "sharp" module

Cannot find module '../build/Release/sharp.node'

- Remove the "node_modules/sharp" directory, run "npm install" and look for errors
- Consult the installation documentation at https://sharp.pixelplumbing.com/en/stable/install/
- Search for this error at https://github.com/lovell/sharp/issues
```

**- If the current behavior is a bug, please provide the steps to reproduce.**

1. Have a JS Netlify function `deploy-building.js` that requires sharp: `const sharp = require('sharp');`
1. Push to Github PR, which notifies Netlify to publish a deploy preview. (We have Netlify configured to deploy PRs automatically.)
1. Site builds, but because `deploy-building.js` did not exist yet, it will not have run during the very first build.
1. Retry deploy in Netlify's UI.
1. `deploy-building.js` runs and logs that something went wrong with sharp.

**- What is the expected behavior?**

I expect my function to be able to find and use the sharp module.

**- Please mention your node.js, and operating system version.**

Locally, I'm using node v11.9.0. I'm on a MacBook Pro running macOS Mojave v10.14.5.

I understand that sharp is a native module, and that it installs a different version for me locally than it installs on Netlify, so I don't think it's a differing environments issue.

I also set the `AWS_LAMBDA_JS_RUNTIME` environment variable on Netlify to `nodejs10.x`, mostly because I was running out of ideas and I thought _maybe_ it would help because of what I had been reading in sharp's installation docs: https://sharp.pixelplumbing.com/en/stable/install/#aws-lambda

At any rate, it was giving me the same errors before I set that variable.

**Comment by caramiki** [comment] 2020-01-15 22:40
Well, `zip-it-and-ship-it` is definitely not including all the necessary files. I installed it locally and ran it on my functions.

Files for `sharp` in my `node_modules`:
```
LICENSE
README.md
binding.gyp
build
docs
install
lib
node_modules
package.json
src
vendor
```

`zip-it-and-ship-it`'s version of `sharp` when I ran it locally:
```
LICENSE
README.md
binding.gyp
docs
install
lib
node_modules
package.json
src
```

Granted I built it on my Mac, so it's not _exactly_ what's going on in the server, but notably the entire `build` directory is missing (and `vendor` too?), which seems to still be needed according to the error in the logs.

**Comment by ehmicky** [comment] 2020-01-16 12:37
Thanks a lot for reporting this!

There is a chance that the latest `zip-it-and-ship-it` beta might solve your issue as we've improved the algorithm for how files are being included. Could you please try `zip-it-and-ship-it@v0.4.0-8` locally and let us know whether this is the case?

**Comment by caramiki** [comment] 2020-01-16 22:27
@ehmicky Well, I tried using the beta release. I tried to unzip `deploy-building.zip` with Mac's default Archive Utility and it gave me the error message `Unable to expand "deploy-building.zip" into "functions-dist". (Error 2 - No such file or directory.)` I deleted the zip and ran `zip-it-or-ship-it` again and tried to open the zip and got the same message.

I tried to unzip it with the Unarchiver and got this error message: `There was a problem while reading the contents of "deploy-building.zip". Data is corrupted` but when I clicked "continue" it _did_ unzip, so… I'm uncertain about the integrity of the contents.

The contents of `sharp` are now:

```
LICENSE
README.md
binding.gyp
build
docs
install
lib
package.json
src
vendor
```

The absence of `sharp`'s own `node_modules` is concerning but it is generating a different zip for sure.

**Comment by DavidWells** [comment] 2020-01-16 22:38
sharp is a pain to bundle with serverless functions (b/c the binary it includes)

We've seen users have more success with https://www.npmjs.com/package/jimp if this meets your requirements.

**Comment by caramiki** [comment] 2020-01-16 22:44
@DavidWells Funny you mention `jimp`. Since reporting this issue, I _did_ try it. 😅 And I _still_ got error messages:

```
6:23:03 PM: 2020-01-16T00:23:03.801Z	undefined	ERROR	Uncaught Exception	{"errorType":"Runtime.ImportModuleError","errorMessage":"Error: Cannot find module 'regenerator-runtime/runtime'","stack":["Runtime.ImportModuleError: Error: Cannot find module 'regenerator-runtime/runtime'","    at _loadUserApp (/var/runtime/UserFunction.js:100:13)","    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)","    at Object.<anonymous> (/var/runtime/index.js:45:30)","    at Module._compile (internal/modules/cjs/loader.js:778:30)","    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)","    at Module.load (internal/modules/cjs/loader.js:653:32)","    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)","    at Function.Module._load (internal/modules/cjs/loader.js:585:3)","    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)","    at startup (internal/bootstrap/node.js:283:19)"]}
6:23:04 PM: 2020-01-16T00:23:04.898Z	undefined	ERROR	Uncaught Exception	{"errorType":"Runtime.ImportModuleError","errorMessage":"Error: Cannot find module 'regenerator-runtime/runtime'","stack":["Runtime.ImportModuleError: Error: Cannot find module 'regenerator-runtime/runtime'","    at _loadUserApp (/var/runtime/UserFunction.js:100:13)","    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)","    at Object.<anonymous> (/var/runtime/index.js:45:30)","    at Module._compile (internal/modules/cjs/loader.js:778:30)","    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)","    at Module.load (internal/modules/cjs/loader.js:653:32)","    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)","    at Function.Module._load (internal/modules/cjs/loader.js:585:3)","    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)","    at startup (internal/bootstrap/node.js:283:19)"]}
6:23:04 PM: Duration: 666.80 ms	Memory Usage: 40 MB	
6:23:04 PM: Unknown application error occurred
Runtime.ImportModuleError
```

I didn't spend much time trying to debug it because, now that I've used both sharp and jimp, I've decided I like sharp more (it wasn't as nice writing code to work with jimp, _and_ it processed images slower, _and_ it made my function take longer to package during deploy), and if they're both broken, may as well keep trying to get the one I like more to work.

**Comment by ehmicky** [comment] 2020-01-24 20:31
@caramiki I am going to look into this.

Could you first please confirm you are using `zip-it-and-ship-it@v0.4.0-8` and not `zip-it-and-ship-it@v0.4.0-7`?

**Comment by ehmicky** [comment] 2020-04-13 12:53
Another deploy exhibiting this bug: https://app.netlify.com/sites/rememberingros/deploys/5e89a8dce5fe8108369ced14

**Comment by sdras** [comment] 2020-04-19 21:17
Any news on this? I'm running into the same issue. I could provide more details but it's basically the same exact report 😅

**Comment by timseverien** [comment] 2020-04-23 15:09
I'm having similar issues. I'm trying to use `argon2` for hashing, which also depends on bindings. Build is succesful but app throws because `argon2.node` is missing.

From the build logs:
>[argon2] Success: "/opt/build/repo/functions/node_modules/argon2/lib/binding/argon2.node" is installed via remote
>...
>Prepping functions with zip-it-and-ship-it 0.3.1

From the function logs:
>Error: Cannot find module '/var/task/node_modules/argon2/lib/binding/argon2.node

**Comment by timseverien** [comment] 2020-04-23 15:51
Went to check out various zip-it-and-ship-it versions, considering @ehmicky [asked](https://github.com/netlify/zip-it-and-ship-it/issues/79#issuecomment-578289882).

Version | Includes `node_modules/argon2/lib/binding/argon2.node`
------- | -------------
`@netlify/zip-it-and-ship-it@0.3.1` | ❌
`@netlify/zip-it-and-ship-it@0.4.0-0` | ❌
`@netlify/zip-it-and-ship-it@0.4.0-1` | Unable to run CLI
`@netlify/zip-it-and-ship-it@0.4.0-2` | Unable to run CLI
`@netlify/zip-it-and-ship-it@0.4.0-3` | ✔
`@netlify/zip-it-and-ship-it@0.4.0-4` | ✔
`@netlify/zip-it-and-ship-it@0.4.0-5` | ✔
`@netlify/zip-it-and-ship-it@0.4.0-6` | ✔
`@netlify/zip-it-and-ship-it@0.4.0-7` | ✔
`@netlify/zip-it-and-ship-it@0.4.0-8` | ✔
`@netlify/zip-it-and-ship-it@0.4.0-14` | ✔

It looks like 0.4.0-3 and onward works well for this particular issue. I see 0.4.0-0 was released 27 Apr 2019—almost a year ago. Any chance 0.4.0 will be released soon? If not, any suggestions for a workaround?

**Comment by timseverien** [comment] 2020-04-23 17:12
Sorry for the spam, but I guess I found a **temporary fix**. I installed [`@netlify/zip-it-and-ship-it@0.4.0-14`](https://www.npmjs.com/package/@netlify/zip-it-and-ship-it) in my _root directory_ (my functions are in a `functions` subdirectory) and Netlify picked that up at build.

**Comment by ehmicky** [comment] 2020-04-27 15:39
The issue seemed to be about both `sharp` and `argon2` being native modules. `zip-it-and-ship-it` (and Netlify Functions) do not currently officially support Node.js native modules (main issue: #69).

We are investigating supporting them though, and it looks like [the core problem](https://github.com/netlify/zip-it-and-ship-it/issues/69#issuecomment-551035275) might be to ensure the native modules are built on the same OS (Linux) and Node.js version as the one used in AWS Lambda. Could you try to set the [`NODE_VERSION`](https://docs.netlify.com/configure-builds/manage-dependencies/#node-js-and-javascript) and the [`AWS_LAMBDA_JS_RUNTIME`](https://docs.netlify.com/functions/build-with-javascript/#runtime-settings) environment variables to use the same Node.js version?

For example, I personally managed to use the `node-sqlite` native module in a Netlify Function by setting `NODE_VERSION` to `10` and `AWS_LAMBDA_JS_RUNTIME` to `nodejs10.x`.

@timseverien Please note unless you directly call `zip-it-and-ship-it`, you should not have to install it directly if you're using the Netlify CLI or the Netlify production CI. For the later, you would need to enable the Build plugins beta to get the latest beta version of `zip-it-and-ship-it` (`0.4.0-14` as of now).

**Comment by timseverien** [comment] 2020-04-28 11:28
@ehmicky ah, I didn't know that, thanks!

**Comment by mikegajda** [comment] 2020-05-23 16:06
Any updates? I've just run into this as well. I've set NODE_VERSION to 12, and AWS_LAMDA_JS_RUNTIME to nodejs12.x, but I get this error
```\nSomething went wrong installing the \"sharp\" module\n\nCannot find module '../build/Release/sharp.node'\nRequire stack:\n- /var/task/node_modules/sharp/lib/constructor.js\n- /var/task/node_modules/sharp/lib/index.js\n- /var/task/handle_opengraph.js\n- /var/task/app.js\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js\n\n- Run \"npm rebuild --verbose sharp\" and look for errors\n- Consult the installation documentation at https://sharp.pixelplumbing.com/install\n- Search for this error at https://github.com/lovell/sharp/issues\n","trace":["Error: ","Something went wrong installing the \"sharp\" module","","Cannot find module '../build/Release/sharp.node'","Require stack:","- /var/task/node_modules/sharp/lib/constructor.js","- /var/task/node_modules/sharp/lib/index.js","- /var/task/handle_opengraph.js","- /var/task/app.js","- /var/runtime/UserFunction.js","- /var/runtime/index.js","","- Run \"npm rebuild --verbose sharp\" and look for errors","- Consult the installation documentation at https://sharp.pixelplumbing.com/install","- Search for this error at https://github.com/lovell/sharp/issues","","    at Object.<anonymous> (/var/task/node_modules/sharp/lib/constructor.js:34:9)","    at Module._compile (internal/modules/cjs/loader.js:1133:30)","    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)","    at Module.load (internal/modules/cjs/loader.js:977:32)","    at Function.Module._load (internal/modules/cjs/loader.js:877:14)","    at Module.require (internal/modules/cjs/loader.js:1019:19)","    at require (internal/modules/cjs/helpers.js:77:18)","    at Object.<anonymous> (/var/task/node_modules/sharp/lib/index.js:3:15)","    at Module._compile (internal/modules/cjs/loader.js:1133:30)","    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)"]}```

**Comment by ehmicky** [comment] 2020-05-25 12:36
Hi @mikegajda,
Unfortunately, we don't have any updates at this point except for my previous comment (which does not seem to fix it for you). This is a part of the more general problem outlined in #69.

**Comment by erezrokah** [comment] 2020-06-03 14:48
Can someone please post a repo that reproduces this issue?
I was able to run `sharp` successfully inside a Netlify function with 2 different configurations:
1. `sharp` installed as a dependency in the [root `package.json`](https://github.com/erezrokah/netlify-build-reproductions/blob/zip-it-and-ship-it/issue_79/package.json#L32)
2. `sharp` installed using [`@netlify/plugin-functions-install-core`](https://github.com/erezrokah/netlify-build-reproductions/blob/zip-it-and-ship-it/issue_79_2/netlify.toml) from a `package.json` [inside the functions directory](https://github.com/erezrokah/netlify-build-reproductions/blob/zip-it-and-ship-it/issue_79_2/functions/package.json#L3)

I created a brand new site, so my function node version is 12, which seems to be a requirement:
https://sharp.pixelplumbing.com/install#aws-lambda

I'm using the default build image `Ubuntu Xenial 16.04 (default)`, installing dependecies with `yarn` and set `YARN_VERSION = "1.22.4"` and `NODE_VERSION = "12"`.

My function is a simple image resizer: https://github.com/erezrokah/netlify-build-reproductions/blob/zip-it-and-ship-it/issue_79/functions/sharp.js

I'll try reproducing with `npm`, but recommend clearing build cache for debugging purposes and try adding the following to the build command:
```bash
rm -rf node_modules/sharp
npm install --arch=x64 --platform=linux sharp
```
As suggested https://sharp.pixelplumbing.com/install#aws-lambda

**Comment by erezrokah** [comment] 2020-06-17 10:53
Is this issue still valid? If so, can someone please post a repo with a reproduction?

**Comment by erezrokah** [comment] 2020-06-22 15:55
Closing this as stale, please comment if still relevant

**Closed** 2020-06-26 20:18 UTC
Labels: type: bug
