### ISSUE TITLE
HTML files are removed from node_modules dependencies

### ISSUE THREAD

**Issue by jarleriksen** [netlify/zip-it-and-ship-it#65] opened 2019-10-24 19:20 UTC
Hi!

I am not exactly sure this is the place to report this.

I started using Netlify Functions where I have a function that runs Google Lighthouse.
I started getting this error: 
`Error: ENOENT: no such file or directory, open '/var/task/node_modules/lighthouse/lighthouse-core/report/html/report-template.html'`

Using Netlify CLI I ran `netlify functions:build` and inspected the zip file it returned, to see that all the html files from node_modules/lighthouse folder has been removed by the build.

I looked at the code for the `functions:build` command and it led me to here.

I am not getting this error when running `netlify dev` so I assume that it doesn't zip the functions.

I might be doing something wrong here and would love an answer.

Thanks a lot!

**Comment by ehmicky** [comment] 2019-10-25 08:55
Hi @jarleriksen,

This is indeed the current behavior, let me explain the background story behind this.

`zip-it-and-ship-it` is taking a function file as input, discovering all the dependent files of that function file and bundling all of them inside a zip archive (to be uploaded to AWS Lambda). We find the dependent files by parsing JavaScript and looking for `require()` statements.

The reason we do this is to make the zip archive as small as possible, which improves serverless performance. 

When it comes to node modules (such as `lighthouse`), if include all the files if the `package.json` `files` property is defined. Otherwise we ignore any file whose extension is `log`, `html`, `md`, `map`, `ts`, `png`, `jpeg`, `jpg`, `gif`, `css` or `patch`.

In your case, `lighthouse` does not use `package.json` `files` but it uses [`.npmignore` instead](https://github.com/GoogleChrome/lighthouse/blob/master/.npmignore). The problem is that this `.npmignore` is not published to npm, so there's no way for us to know it's being used.

I've included a fix for this problem (04d380fecbdefd5b25737c0a6f4f57b4b9ddb29e) as part of #48. Please note that this PR is a major rewrite of this library and as such we are currently beta testing it, which might unfortunately take many weeks.

**Comment by jarleriksen** [comment] 2019-10-25 09:10
Hey @ehmicky,
Thanks a lot for your answer!

I am very excited for when the release comes out!

Basically my only solution right now, would be to zip the functions myself and manually upload them to Netlify via the CLI, correct? :)

It's not a huge issue as I don't deploy functions multiple times a day.

Thanks!

**Comment by ehmicky** [comment] 2019-10-25 09:13
Yes exactly @jarleriksen, that should work :)

**Comment by jarleriksen** [comment] 2019-11-01 14:51
For anyone else running into this issue:

I couldn't get custom zips to work, so I ended up just rolling my own AWS Lambda Function and not using Netlify Functions.

This is obviously the less preferred way as Netlify Functions are awesome.

**Comment by ehmicky** [comment] 2019-11-28 12:36
@jarleriksen you should now be able to access the fix I was mentioning above by signing up to the [new Build beta](https://www.netlify.com/build/plugins-beta/) if you wanted to give it a shot :)

**Closed** 2019-11-29 09:51 UTC
Labels: bug
